### ISSUE TITLE
Make a macro for ptrace() to exit on failure

### ISSUE THREAD

**Issue by Arinerron** [Arinerron/heaptrace#52]

**Comment by tcheinen** [comment]
Are you looking to say something and exit heaptrace if ptrace fails?  My brain initially said "break in the traced program" but that doesn't make sense if ptrace fails lol. Wanted to make sure I had the right idea before I started working

**Comment by Arinerron** [comment]
@tcheinen  Yup. Like to define a compiler macro `PTRACE(...)`. Sorry for not adding more description. I kinda use these as a notepad haha. Appreciate it!

**Comment by tcheinen** [comment]
Is there a designated utility file for macros and such? I didn't see anything like that

**Comment by Arinerron** [comment]
Not yet, feel free to make one! I've been using logging.h (see ABORT, ASSERT, ASSERT_NICE, etc) since it's included in nearly every file, but we do kinda need one

**Comment by tcheinen** [comment]
aw man im too slow lmao; i'll have to take a look at some other issues bc this is real cool
