### ISSUE TITLE
heaptrace error: Failed to find target binary in process mapping (!bin_pme). Please report this!

### ISSUE THREAD

**Issue by kotee4ko** [Arinerron/heaptrace#61]
Hi.

Awesome project, really MUSTHAVE!

But I catch some troubles:

1) It doesn't compile because of undefined `sigabbrev_np()`
Quick reading of `man sigabbrev_np` push me to change it to `strsignal()`, the binary compiled ok.

But it doesn't launch with any attrs throwing the message from header.

Checked on `libc-2.31.so` and `libc-2.28.so`. Same results.

I didn't find any information about minimal required libc version. Am I was looking bad?

Thanks.

**Comment by Arinerron** [comment]
I should also add that I'd like to support all glibc versions if possible. This seems to be specific to your OS somehow though (perhaps the formatting of /proc/pid/maps?), not the glibc version.

So one more thing, if you don't mind: could you send the output of `cat /proc/self/maps`? Just to make sure it's formatted the same way.

**Comment by kotee4ko** [comment]
Hi. Just fall asleep yesterday, sorry. I'll check all stuff and report back in a moment
