### ISSUE TITLE
Enhance: handle non-deterministic heap operations

### ISSUE THREAD

**Issue by Kyle-Kyle** [Arinerron/heaptrace#64]
Since this project invokes gdb later, it's this project's job to decide when the wanted program state is achieved and then launches gdb for debugging. The current approach, counting heap operation numbers, is not a reliable way to determine program state because real-world programs may invoke different numbers of heap operations each time to reach a specific program state (for example, initialization code behaves differently each time).

I suggest supporting another interface that allows users to set a breakpoint at a specific address and using the times this breakpoint is invoked as an indicator whether the execution should be passed to gdb.

**Comment by Kyle-Kyle** [comment]
maybe it can be merged into the `--break` interface.

**Comment by Arinerron** [comment]
Super close on this! But I'm braindead from looking at code for too long so I'm gonna finish it another day. My progress is @ https://github.com/Arinerron/heaptrace/pull/65

It works for all oid examples. It also works for most of the address examples, but `libc` variable doesn't work yet, and the count feature is broken
